version: "3.8"

services:
  localpostgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: mydb
    ports:
        - "5439:5432"
    volumes: 
        - mydb:/var/lib/postgresql/data

# Store locally on the machine.
volumes:
    mydb:
        driver: local
